// Mocks generated by Mockito 5.4.6 from annotations
// in blockly/test/market_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blockly/feature/enums/socket_status_enum.dart' as _i7;
import 'package:blockly/feature/models/mini_ticker.dart' as _i6;
import 'package:blockly/feature/services/json_parser/websocket_isolate_parser.dart'
    as _i8;
import 'package:blockly/feature/services/network/dio_service.dart' as _i3;
import 'package:blockly/feature/services/web_socket/web_socket_service.dart'
    as _i5;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioService extends _i1.Mock implements _i3.DioService {
  MockDioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get baseOptions =>
      (super.noSuchMethod(
            Invocation.getter(#baseOptions),
            returnValue: _FakeBaseOptions_0(
              this,
              Invocation.getter(#baseOptions),
            ),
          )
          as _i2.BaseOptions);

  @override
  set baseOptions(_i2.BaseOptions? option) => super.noSuchMethod(
    Invocation.setter(#baseOptions, option),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<T?> request<T>({
    required String? url,
    required T Function(Map<String, dynamic>)? fromJson,
    Map<String, dynamic>? queryParameters,
    Object? data,
    String? requestType = 'GET',
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#request, [], {
              #url: url,
              #fromJson: fromJson,
              #queryParameters: queryParameters,
              #data: data,
              #requestType: requestType,
              #headers: headers,
            }),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Stream<List<T>> requestStreaming<T>({
    required String? url,
    required T Function(Map<String, dynamic>)? fromJson,
    Object? data,
    Map<String, dynamic>? queryParameters,
    String? requestType = 'GET',
    Map<String, dynamic>? headers,
    int? chunkSize = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestStreaming, [], {
              #url: url,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
              #requestType: requestType,
              #headers: headers,
              #chunkSize: chunkSize,
            }),
            returnValue: _i4.Stream<List<T>>.empty(),
          )
          as _i4.Stream<List<T>>);
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTickerWebSocketService extends _i1.Mock
    implements _i5.WebSocketService<_i6.MiniTicker> {
  MockTickerWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i7.SocketStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i4.Stream<_i7.SocketStatus>.empty(),
          )
          as _i4.Stream<_i7.SocketStatus>);

  @override
  _i4.Stream<_i6.MiniTicker> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: _i4.Stream<_i6.MiniTicker>.empty(),
          )
          as _i4.Stream<_i6.MiniTicker>);

  @override
  set channelFactory(_i5.WebSocketChannelFactory? value) => super.noSuchMethod(
    Invocation.setter(#channelFactory, value),
    returnValueForMissingStub: null,
  );

  @override
  void setParser(_i8.Parser<_i6.MiniTicker>? parser) => super.noSuchMethod(
    Invocation.method(#setParser, [parser]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> connect(String? url, {bool? useIsolate = false}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [url], {#useIsolate: useIsolate}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void send(dynamic message) => super.noSuchMethod(
    Invocation.method(#send, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
